frontend:
  image:
    repository: "<PROD_FRONTEND_ECR_URL>"
    tag: "prod-1.0.0"

backend:
  image:
    repository: "<PROD_BACKEND_ECR_URL>"
    tag: "prod-1.0.0"

service:
  type: ClusterIP
  port: 80
