frontend:
  image:
    repository: "<DEV_FRONTEND_ECR_URL>"
    tag: "dev-1.0.0"

backend:
  image:
    repository: "<DEV_BACKEND_ECR_URL>"
    tag: "dev-1.0.0"

service:
  type: ClusterIP
  port: 80
